config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, skip: [:sessions]
  devise_scope :admin_user do
    get  'login' => 'devise/sessions#new', as: :new_admin_user_session
    post 'login' => 'devise/sessions#create', as: :admin_user_session
    get  'logout' => 'devise/sessions#destroy', as: :destroy_admin_user_session
  end
  root 'home#index'
  get 'home/dashboard'

  devise_for :users, skip: [:sessions], controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  devise_scope :user do
    get  'login' => 'devise/sessions#new', as: :new_user_session
    post 'login' => 'devise/sessions#create', as: :user_session
    get  'logout' => 'devise/sessions#destroy', as: :destroy_user_session
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v1 do
      namespace :attendances do
        post "/" , :action => "record"
      end
    end
  end

  namespace :admin do
    get '/' => 'admin#index'
    resources :attendances, only: :index
  end

  resources :attendances, only: :index do
    collection do
      post :record
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  devise :database_authenticatable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  enum status: { stay: 0, leave: 1 }

  def self.record(user)
    today = Date.today
    attendance = self.new(user: user, date: today)
    last_record = where(user: user, date: today).last
    case last_record.try(&:status).try(&:to_sym)
    when :stay
      attendance.status = :leave
      last_record.duration = ((Time.now - last_record.created_at)/3600.0).round(2)
    when :leave
      attendance.status = :stay
    else
    end
    ApplicationRecord.transaction do
      last_record.save! if last_record.try(&:changed?)
      attendance.save!
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :trackable, :omniauthable, omniauth_providers: %i(google)
  before_create :generate_uuid

  def generate_uuid
    random_code = nil
    loop do
      random_code = SecureRandom.urlsafe_base64(40, false)
      break unless User.where(uuid: random_code).exists?
    end
    self.uuid = random_code
  end

  protected

  def self.find_for_google(auth)
    user = User.find_or_initialize_by(email: auth.info.email)

    if user.new_record?
      user = User.create(
        email:    auth.info.email,
        name:     auth.info.name,
        provider: auth.provider,
        uid:      auth.uid,
        token:    auth.credentials.token,
        password: Devise.friendly_token[0, 20],
      )
    end
    user
  end
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  def index
  end
end

app/controllers/admin/attendances_controller.rb
class Admin::AttendancesController < ApplicationController
  def index
    @records = Attendance.where(date: Date.today, user: User.first)
  end
end

app/controllers/api/v1/attendances_controller.rb
class Api::V1::AttendancesController < Api::V1::BaseController
  def record
    Attendance.record(current_user)
    render text: 'ok', status: 200
  end
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::Base
  class UnauthorizedError < StandardError; end
  before_action :authorize

  rescue_from UnauthorizedError do
    render text: "Unauthorized!", status: 401
  end

  def authorize
    begin
      @current_user = User.find_by!(uuid: request.headers[:Uuid])
    rescue => e
      raise UnauthorizedError
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    home_dashboard_path
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def index
    @records = Attendance.where(user: current_user, date: Date.today).to_a
  end

  def record
    Attendance.record(current_user)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
  end

  def dashboard
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google
    @user = User.find_for_google(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/admin/index.html.slim
| hoge

app/views/admin/attendances/index.html.slim
table
  tr
  td ステータス
  td 勤務時間
  - @records.each do |r|
    tr
      td= r.status
      td= r.duration

app/views/attendances/index.html.slim
.panel.panel-primary
  .panel-heading
    h3
      | 今日の勤務状況

  .panel.panel-default
    .panel-heading
      table.table
        thead
          tr
            th ステータス
            th 勤務時間
            th 登録日時
            th 合計勤務時間
          - @records.each do |r|
            tr
              td= r.status
              td= r.duration
              td= r.created_at
              td=
          tr
            td
            td
            td
            td= @records.sum(&:duration)

app/views/home/dashboard.html.slim
.row
  .center.text-center
    now
  .dashboard
    = button_to '打刻', record_attendances_path, action: :post, class: 'btn btn-primary impress'

app/views/layouts/_footer.html.slim
footer.footer
  .container
    .footer-copyright.text-center
      = "© #{Time.zone.now.year} Kintai by"
      span.link
        = link_to "@reizist", 'https://twitter.com/reizist'

app/views/layouts/_header.html.slim
nav.navbar.navbar-default
  .container
    .container-fluid
      /! Brand and toggle get grouped for better mobile display
      .navbar-header
        button.navbar-toggle.collapsed aria-expanded="false" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button"
          span.sr-only Toggle navigation
          span.icon-bar
          span.icon-bar
          span.icon-bar
        = link_to 'Kintai', home_dashboard_path, class: 'navbar-brand'
      - if user_signed_in?
        ul.nav.navbar-nav
          li= link_to '勤怠管理', attendances_path
      /! Collect the nav links, forms, and other content for toggling
      #bs-example-navbar-collapse-1.collapse.navbar-collapse
        ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            li.dropdown
              a.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
                | メニュー
                span.caret
              ul.dropdown-menu
                li.divider role="separator"
                li
                  = link_to 'ログアウト', destroy_user_session_path
          - else
            li
              = link_to 'ログイン', user_google_omniauth_authorize_path

app/views/layouts/_messages.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
    .alert.alert-dismissable(class="alert-#{name == :notice ? "success" : "danger"}")
      button.close(data-dismiss="alert" aria-hidden="true") &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Kintai
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/header'
    .main
      .container
        .row
          = yield
    = render 'layouts/footer'